export const AllCharacters = [
  "Hoshino Ichika",
  "Tenma Saki",
  "Mochizuki Honami",
  "Hinomori Shiho",
  "Hanasato Minori",
  "Kiritani Haruka",
  "Momoi Airi",
  "Hinomori Shizuku",
  "Azusawa Kohane",
  "Shiraishi An",
  "Shinonome Akito",
  "Aoyagi Toya",
  "Tenma Tsukasa",
  "Otori Emu",
  "Kusanagi Nene",
  "Kamishiro Rui",
  "Yoisaki Kanade",
  "Asahina Mafuyu",
  "Shinonome Ena",
  "Akiyama Mizuki",
  "Hatsune Miku",
  "Kagamine Rin",
  "Kagamine Len",
  "Megurine Luka",
  "MEIKO",
  "KAITO",
  "L/n Miku",
  "MMJ Miku",
  "VBS Miku",
  "WxS Miku",
  "N25 Miku",
  "L/n Rin",
  "MMJ Rin",
  "VBS Rin",
  "WxS Rin",
  "N25 Rin",
  "L/n Len",
  "MMJ Len",
  "VBS Len",
  "WxS Len",
  "N25 Len",
  "L/n Luka",
  "MMJ Luka",
  "VBS Luka",
  "WxS Luka",
  "N25 Luka",
  "L/n MEIKO",
  "MMJ MEIKO",
  "VBS MEIKO",
  "WxS MEIKO",
  "N25 MEIKO",
  "L/n KAITO",
  "MMJ KAITO",
  "VBS KAITO",
  "WxS KAITO",
  "N25 KAITO",
];

export const RARITY_COLORS: Record<number, string> = {
  1: "bg-gray-400",
  2: "bg-green-400",
  3: "bg-blue-400",
  4: "bg-purple-400",
};

export const notAllowedTypes = [
  "movie_exclusive",
  "bday",
  "limited_collab",
  "unit_limited",
];
